1.NumPy array banana.

In [3]:
import numpy as np

#list se array banana
order_values = np.array([250,1200,45,3400,89,670])
print(order_values)
print(type(order_values))
print(order_values.shape)
print(order_values.dtype)

[ 250 1200   45 3400   89  670]
<class 'numpy.ndarray'>
(6,)
int64


2.Array vs List - speed aur behaviour ka fark:

In [4]:
# List mein har element pe operation karne ke liye loop chahiye
prices_list = [10, 20, 30]
discounted_list = [p * 0.9 for p in prices_list]   # list comprehension
print(discounted_list)

# NumPy array mein directly operation ho jaata hai (vectorized)
prices_array = np.array([10, 20, 30])
discounted_array = prices_array * 0.9
print(discounted_array)

[9.0, 18.0, 27.0]
[ 9. 18. 27.]


Note - NumPy arrays par mathematical operations element-wise automatically apply hote hain, aur yeh Python lists se bahut zyada fast hota hai bade datasets par (kyunki NumPy internally C mein likha hai).

3.2D Arrays (matrix jaisa — jaise ek chhota transactions table):

In [5]:
# Rows = orders, Columns = [Quantity, Price]
transactions_sample = np.array([
    [12, 6.95],
    [48, 2.10],
    [24, 3.75],
    [6, 15.00]
])
print(transactions_sample.shape)   # (4, 2)
print(transactions_sample[0])      # pehli row
print(transactions_sample[:, 0])   # sirf pehla column (Quantity)
print(transactions_sample[:, 1])   # sirf dusra column (Price)

(4, 2)
[12.    6.95]
[12. 48. 24.  6.]
[ 6.95  2.1   3.75 15.  ]


4.Basic operations — sum, mean, max, min:

In [6]:
quantities = transactions_sample[:, 0]
prices = transactions_sample[:, 1]

print("Total quantity:", np.sum(quantities))
print("Average price:", np.mean(prices))
print("Max price:", np.max(prices))
print("Min quantity:", np.min(quantities))
print("Std deviation of prices:", np.std(prices))

Total quantity: 90.0
Average price: 6.95
Max price: 15.0
Min quantity: 6.0
Std deviation of prices: 4.963995366637644


5.Revenue calculate karna — element-wise multiplication (Quantity × Price, jaisa hum SQL mein karte the):

In [7]:
revenue_per_order = quantities * prices
print(revenue_per_order)
print("Total revenue:", np.sum(revenue_per_order))

[ 83.4 100.8  90.   90. ]
Total revenue: 364.20000000000005


6.. Boolean indexing/filtering (bahut important pattern — Pandas mein bhi yehi concept use hoga):

In [8]:
# Sirf woh orders dikhao jinka revenue > 50
high_value_mask = revenue_per_order > 50
print(high_value_mask)                      # True/False array
print(revenue_per_order[high_value_mask])   # sirf True wale values

[ True  True  True  True]
[ 83.4 100.8  90.   90. ]


7.Array creation shortcuts (kaam aate hain testing/dummy data ke liye):

In [9]:
zeros = np.zeros(5)              # [0,0,0,0,0]
ones = np.ones(5)                # [1,1,1,1,1]
range_arr = np.arange(0, 100, 10)  # [0,10,20,...,90]
random_arr = np.random.randint(1, 100, size=10)  # 10 random numbers 1-100
print(zeros, ones, range_arr, random_arr)

[0. 0. 0. 0. 0.] [1. 1. 1. 1. 1.] [ 0 10 20 30 40 50 60 70 80 90] [58 98 76 13 81 71 62 62 58 32]


Practice questions.

1.Ek NumPy array banao 20 random order values ka (np.random.randint(10, 5000, size=20)), phir uska mean, median (np.median()), aur standard deviation nikalo.

In [1]:
import numpy as np

# 10 se 5000 ke beech 20 random orders ka NumPy array banana
orders_array = np.random.randint(10, 5000, size=20)
print(f"Orders Array:\n{orders_array}\n")

# 2. Mean (Average) nikalna
mean_value = np.mean(orders_array)

# 3. Median (Beech ki value) nikalna
median_value = np.median(orders_array)

# 4. Standard Deviation (Variation / Failaav) nikalna
std_value = np.std(orders_array)

# Results print karna
print(f"Mean (Average): {mean_value:.2f}")
print(f"Median: {median_value}")
print(f"Standard Deviation: {std_value:.2f}")

Orders Array:
[3301 1338 4556  769 1403 4891 4279  410 1494 1993 2373  437   57  386
  923 2737  972 4641  234 1957]

Mean (Average): 1957.55
Median: 1448.5
Standard Deviation: 1559.70


2.Boolean indexing use karke un values ko nikalo jo array ke mean se zyada hain.

In [2]:
# Mean se zyada wali values nikalna (Boolean Indexing)
high_orders = orders_array[orders_array > mean_value]

print(f"Mean (Average) tha: {mean_value:.2f}")
print(f"Mean se zyada values: {high_orders}")

Mean (Average) tha: 1957.55
Mean se zyada values: [3301 4556 4891 4279 1993 2373 2737 4641]


3.Do arrays banao — quantity aur price (5-5 elements ke) — aur unka element-wise product (revenue) nikalo, phir total revenue print karo.

In [3]:
import numpy as np

# 1. Quantity aur Price ke 5-5 elements wale do arrays banana
quantity = np.array([2, 5, 1, 4, 3])
price = np.array([100, 250, 1200, 50, 500])

# 2. Element-wise product (Revenue) nikalna
# NumPy seedhe corresponding elements ko multiply kar deta hai (jaise quantity[0] * price[0])
revenue = quantity * price

# 3. Total revenue nikalna (saare revenues ka sum)
total_revenue = np.sum(revenue)

# Results print karna
print(f"Quantity: {quantity}")
print(f"Price: {price}")
print(f"Revenue (Item-wise): {revenue}")
print(f"Total Revenue: {total_revenue}")

Quantity: [2 5 1 4 3]
Price: [ 100  250 1200   50  500]
Revenue (Item-wise): [ 200 1250 1200  200 1500]
Total Revenue: 4350
